[Issue #390]added the client._generate._get_known_symbols
enthought/comtypes pull request #391
Opened 2022-12-03 20:18 UTC by muddi900

Fixes: Issue #390, uses pre-PEP585 typing annotations.

2022-12-04 03:15 UTC, junkmd requested changes

2022-12-04 03:15 UTC, junkmd commented on comtypes/client/_generate.py
> +    from typing import Any, Tuple, List, Optional, Dict, Union as _UnionT
👍

2022-12-04 03:15 UTC, junkmd commented on comtypes/client/_generate.py
> +            tlib_string, _file_ and os.path.dirname(_file_))
Please revert it since it is not related to #390

2022-12-04 03:15 UTC, junkmd commented on comtypes/client/_generate.py
> +                    "GetModule(%s): could not resolve to a filename", tlib)
Please revert it since it is not related to #390

2022-12-04 03:15 UTC, junkmd commented on comtypes/client/_generate.py
> +        assert not (os.path.isabs(pathname)) or os.path.exists(pathname)
Please revert it since it is not related to #390

2022-12-04 03:15 UTC, junkmd commented on comtypes/client/_generate.py
> +                       for v in winreg.EnumKey(key, 0).split(".")]
Please revert it since it is not related to #390

2022-12-04 03:15 UTC, junkmd commented on comtypes/client/_generate.py
> +    known_symbols: Dict[str, str] = {}
This package still supports Python 2.7.

You should write type annotations by comments in the way of [PEP484](https://peps.python.org/pep-0484/#suggested-syntax-for-python-2-7-and-straddling-code).

For example, here will be...
```py
def _get_known_symbols():
    # type: () -> Dict[str, str]
    known_symbols = {}  # type: Dict[str, str]
    ...
```

2022-12-04 03:15 UTC, junkmd commented on comtypes/client/_generate.py
> +            names: List[str] = mod.__known_symbols__
You should write type annotations by comments in the way of [PEP484](https://peps.python.org/pep-0484/#suggested-syntax-for-python-2-7-and-straddling-code).

2022-12-05 08:01 UTC, junkmd requested changes

2022-12-05 08:01 UTC, junkmd commented on .gitignore
> +custom location
Please revert here.

2022-12-05 08:10 UTC, junkmd requested changes

2022-12-05 08:10 UTC, junkmd commented on comtypes/client/_generate.py
> +
Please delete this blank line.

2022-12-05 08:10 UTC, junkmd commented on comtypes/client/_generate.py
> +    known_symbols = {} # type: Dict[str, str]
Please use two spaces before a comments

2022-12-05 08:10 UTC, junkmd commented on comtypes/client/_generate.py
> +            names = mod.__known_symbols__ # type: List[str]
Please use two spaces before a comments

2022-12-05 10:13 UTC, junkmd requested changes
Your environment only setting are should not add to the PR.

2022-12-05 11:54 UTC, junkmd requested changes
And please do such as `git rm "custom location" -r`.

"Your environment only setting are should not add to the PR." is **no** means to say that "You can add your non-ignored test outputs to the PR freely".

2022-12-05 11:54 UTC, junkmd commented on comtypes/client/_generate.py
> +     # type: () -> Dict[str,str]
Strange spacing...
Please fix it.
```py
def _get_known_symbols():
    # type: () -> Dict[str, str]
    ...
```

2022-12-05 12:01 UTC, junkmd commented
@muddi900 

If you are not sure what the commands mean or what the final destination should be, please feel free to ask questions.

2022-12-06 08:27 UTC, muddi900 commented
> @muddi900
> 
> If you are not sure what the commands mean or what the final destination should be, please feel free to ask questions.

Is there a contribution doc? I couldn't find it in the docs.

2022-12-06 08:49 UTC, junkmd commented
@muddi900 

> a contribution doc?

I'm working on that, please see #387.

I have recently been attempting to increase contributors in this community.

Therefore, there are still imperfections. Sorry.

2022-12-06 14:52 UTC, junkmd commented
@muddi900 

As a recommendation, you should deactivate the auto-formatter in VSCode's workspace settings.

Applying your formatter to a project that does not use a formatter or uses a different type of formatter and settings, such as this project, can cause unexpected changes.

2022-12-07 23:57 UTC, junkmd approved these changes
Type annotations are fixed. Thanks @muddi900 

<details>
<summary>misc</summary> 

https://ci.appveyor.com/project/pywinauto/pywinauto/builds/45610244
</details>

2022-12-07 23:58 UTC, merged