Improve error message on non Win
enthought/comtypes pull request #423
Opened 2022-12-25 15:56 UTC by CristiFati

#422 in a different branch.

2022-12-25 15:59 UTC, CristiFati commented
In the 1st commit I tried to keep things *Python 2* compatible as well (that's why I didn't use `raise from` from the beginning).

2022-12-25 23:17 UTC, junkmd requested changes

2022-12-25 23:17 UTC, junkmd commented on comtypes/__init__.py
> +        "https://learn.microsoft.com/en-us/windows/win32/com."))
The final `.` in this line is not necessary.
The dots in the URL and the dots as punctuation are confusing.

2022-12-25 23:17 UTC, junkmd commented on comtypes/__init__.py
> +        "",
Is this first blank line necessary?

2022-12-26 09:02 UTC, CristiFati commented
I placed the empty line to be (what I consider) clearer. Of course it can be removed. Below are the differences (w / wo it):

```
[cfati@cfati-5510-0:/mnt/e/Work/Dev/GitHub/CristiFati/comtypes/src]> python -c "import comtypes"
Traceback (most recent call last):
  File "/mnt/e/Work/Dev/GitHub/CristiFati/comtypes/src/comtypes/__init__.py", line 8, in <module>
    from _ctypes import COMError
ImportError: cannot import name 'COMError' from '_ctypes' (/usr/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/mnt/e/Work/Dev/GitHub/CristiFati/comtypes/src/comtypes/__init__.py", line 16, in <module>
    raise ImportError(msg) from e
ImportError:
COM technology not available (maybe it's the wrong platform).
Note that COM is only supported on Windows.
For more details, please check: https://learn.microsoft.com/en-us/windows/win32/com
```
```
[cfati@cfati-5510-0:/mnt/e/Work/Dev/GitHub/CristiFati/comtypes/src]> python -c "import comtypes"
Traceback (most recent call last):
  File "/mnt/e/Work/Dev/GitHub/CristiFati/comtypes/src/comtypes/__init__.py", line 8, in <module>
    from _ctypes import COMError
ImportError: cannot import name 'COMError' from '_ctypes' (/usr/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/mnt/e/Work/Dev/GitHub/CristiFati/comtypes/src/comtypes/__init__.py", line 15, in <module>
    raise ImportError(msg) from e
ImportError: COM technology not available (maybe it's the wrong platform).
Note that COM is only supported on Windows.
For more details, please check: https://learn.microsoft.com/en-us/windows/win32/com
```

2022-12-26 10:09 UTC, junkmd requested changes
Such as `ImportError: COM technology...`, it would be easier to understand if there is a summary of the information beside it rather than under it.
Please remove the first line break.

2022-12-26 11:10 UTC, junkmd commented
CI is failed…
I will close and reopen this to re-run appveyor.

2022-12-26 12:36 UTC, junkmd commented
CIs are passed.

<details>
<summary>memo</summary>

https://ci.appveyor.com/project/cfarrow/comtypes/builds/45775836
https://ci.appveyor.com/project/pywinauto/pywinauto/builds/45775876
</details>

2022-12-26 12:36 UTC, junkmd approved these changes
Error message for using on non-Windows environments is improved. Thanks @CristiFati

2022-12-26 12:37 UTC, merged