Implement static import for `ISequentialStream` (#529)
enthought/comtypes pull request #578
Opened 2024-06-29 06:10 UTC by jonschz

See #529. I migrated the code from the old `istream-issue` branch to the latest `main` branch. Let me know if anything else needs to be done.

Closes #529

2024-06-30 04:49 UTC, junkmd requested changes
I have added the parts of the test that I was concerned about.

There are no problems with the production codebase or its behavior.

As remaining tasks to merge this PR, we need to work on naming and writing comments.

2024-06-30 04:49 UTC, junkmd commented on comtypes/objidl.py
I feel that this module should be renamed to `stream.py`.

I originally named it `objidl.py` based on `objidl.h`.
However, I realized that if we continue to maintain it in this approach, we will have to create and define utilities related to `IStream` in `combaseapi.py` and `shlwapi.py`, which will result in a loss of cohesion.

What do you think?

2024-07-03 13:16 UTC, junkmd commented
I have come across a repository that makes `RemoteRead` usable by directly modifying the module generated in `comtypes.gen` (such as changing `pv` to `["in", "out"]`). If this PR is merged, that approach will be no more, and that codebase may not work.

However, that approach involves modifying the codebase within the `comtypes` package. In other words, it is essentially synonymous with forking and applying a custom patch for use.

Therefore, I think that those codebases becoming inoperable due to this change does not constitute "breaking backward compatibility".

2024-07-05 05:38 UTC, jonschz commented on comtypes/objidl.py
> +        return pv, pcb_read.contents.value
I added a small comment.

2024-07-05 05:38 UTC, jonschz commented on comtypes/objidl.py
Makes sense, I changed it.

2024-07-05 05:39 UTC, jonschz commented on comtypes/objidl.py
> +        COMMETHOD(
I added an explanation. Feel free to change it if you feel that it can be improved. Otherwise, feel free to resolve.

2024-07-05 05:42 UTC, jonschz commented
> In other words, it is essentially synonymous with forking and applying a custom patch for use.

I agree with that. If all the downstream code we break is code that changed this packages behaviour, that is not a "breaking change" in my opinion, since they did not use part of our official API. Giving them a heads up won't hurt, but whenever you do something like that, you pretty much have to do version pinning (or blame yourself if an external update breaks your package).

The part of the official API that we *did* change has never worked in the past to begin with, so it's quite a stretch to call that a "breaking change" in my opinion.

2024-07-06 01:26 UTC, junkmd commented
> Giving them a heads up won't hurt, but whenever you do something like that, you pretty much have to do version pinning (or blame yourself if an external update breaks your package).

I am planning to include this change in the release of version 1.4.5.
This means that we will explicitly state that the 'custom patch' approach to `RemoteRead` under `comtypes.gen` can only be used up to version 1.4.4.

For example, if there is a 'custom patch' version of `RemoteRead` that 
> sets the first parameter to be `['in', 'out']`

as you mentioned in https://github.com/enthought/comtypes/issues/474#issue-1536002087, it is necessary to make the following changes:
```diff
buffer_size = 1024
- pv = (c_ubyte * buffer_size)()
- read_buffer, data_read = stream.RemoteRead(pv, buffer_size)
+ read_buffer, data_read = stream.RemoteRead(buffer_size)
```

Since it is impossible for us to investigate how widely the 'custom patch' is used in the world, I do NOT plan to find and go around individual repositories to encourage caution.

> The part of the official API that we _did_ change has never worked in the past to begin with, so it's quite a stretch to call that a "breaking change" in my opinion.

I agree with this.
I think making something that was causing some kind of error at the time of the call usable is in the realm of 'bug fixes'.
I do NOT think it's a "breaking change" if a user's ad hoc workaround starts causing errors when a bug has been fixed upstream.

I will also mention that this change only affects `ISequentialStream` defined within the module generated by `GetModule` in `comtypes.gen`, and does not break codebases that define and implement `ISequentialStream` (and `tagSTATSTG` and `IStream`) statically on their own.

2024-07-06 01:28 UTC, junkmd commented
I recognize that there are (other than `ISequentialStream`'s `RemoteRead`) methods that must be overriden because the codebase generated by `codegenerator` is not usable as is.
However, in this project, I am reluctant to statically define those interfaces and methods anything and everything.
Further discussion is needed in a separate scope from #474 for interfaces other than `ISequentialStream`.

I am considering accepting #578 is because `IStream` is the de facto standard for handling streams in COM, and I think it is in the community's profit to make `RemoteRead` usable.

2024-07-06 03:14 UTC, junkmd approved these changes

2024-07-06 03:20 UTC, merged

2024-07-06 09:48 UTC, jonschz commented
> I recognize that there are (other than `ISequentialStream`'s `RemoteRead`) methods that must be overriden because the codebase generated by `codegenerator` is not usable as is.

I am sure that other examples will show up over time. As I don't see an automatic fix at the moment, I suggest we just implement them by hand as they come in. The fact that `ISequentialStream` is (afaik) the only one reported so far suggests that the problem is not extremely frequent.

Thank you for your efforts and contributions to this project!