KeyError: <class 'ctypes.HRESULT'>, _ctype_to_vartype, HRESULT: VT_HRESULT
enthought/comtypes pull request #670
Opened 2024-11-27 10:03 UTC by davidschranz

Pull request for changes described in https://github.com/enthought/comtypes/issues/668

2024-11-27 10:44 UTC, junkmd requested changes
Thank you for contributing.

We need to write test code as well.

The test will include assertions ensuring that the definition of `_midlSAFEARRAY(HRESULT)` does not cause an error, while calling `_midlSAFEARRAY(HRESULT).create` raises a `TypeError`.

There are multiple modules for testing safearray, so I am currently looking for the most appropriate place to add the test.

2024-11-27 10:44 UTC, junkmd commented on comtypes/safearray.py
> +                    )
Formatting issue.

```diff
-                    )
+                )
```

2024-11-27 11:59 UTC, junkmd requested changes
I believe that `test/test_midl_safearray_create.py` is the most suitable location to test this behavior.

You could add a test like the following: 

https://github.com/enthought/comtypes/blob/fb15f91d12aedfff1782150ff8e6bc02da4c8257/comtypes/test/test_midl_safearray_create.py#L1-L4

```diff
 # coding: utf-8

-from ctypes import c_int, pointer, POINTER
+from ctypes import c_int, pointer, HRESULT, POINTER
 import unittest
```

https://github.com/enthought/comtypes/blob/fb15f91d12aedfff1782150ff8e6bc02da4c8257/comtypes/test/test_midl_safearray_create.py#L82-L87

```diff
                 self.assertEqual(unpacked.answer, 42)
                 self.assertEqual(unpacked.needs_clarification, True)

+    def test_HRESULT(self):
+        hr = HRESULT(1)
+        sa_type = comtypes.safearray._midlSAFEARRAY(HRESULT)
+        with self.assertRaises(TypeError):
+            sa_type.create([hr], extra=None)
+        with self.assertRaises(TypeError):
+            sa_type.create([hr])
+
     def test_ctype(self):
         extra = None
         cdata = c_int(1)
```

2024-11-27 23:11 UTC, junkmd approved these changes
Thanks.

2024-11-27 23:19 UTC, merged

2024-11-28 07:28 UTC, davidschranz commented
Thank you very much for your help!

2024-11-28 11:33 UTC, junkmd commented
You're welcome.
This time, the changes to the production code were minimal, and the tests were also kept to a minimum.
Above all, your excellent reproducer and your responsiveness when I asked for verification made this PR much easier to merge.